# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: E2E Test

on: [push, pull_request]

jobs:
  e2e_test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: add venv
      run: |
        pwd
        ls -a
        cd e2e_tests
        pwd
        
        python3 -m venv --clear ../venv
        cd ..
        ls -a
    - name: install dependency
      run: |
        source ../venv/bin/activate
        which python

        
      